import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"], // Specify the font weights you need
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutType = {
  children: React.ReactNode;
};
export default function RootLayout({ children }: RootLayoutType) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div
          className={`min-h-screen flex flex-col justify-between relative bg-[var(--mainBg)]`}
        >
          <Header />
          <main className="flex-1 container mx-auto lg:p-10">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
